spring.application.name=chatbot-service
server.port=4008

# ---------------------------
# Spring AI Ollama Config
# ---------------------------
# Point to your local Ollama installation
spring.ai.ollama.base-url=http://localhost:11434

# Specify the exact model you downloaded in Step 2
spring.ai.ollama.chat.options.model=llama3.1

# Temperature (0.0 is analytical/strict, 1.0 is creative)
spring.ai.ollama.chat.options.temperature=0.4