spring.application.name=patient-service
spring.datasource.url=jdbc:postgresql://patient-postgres:5432/patientdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=patient_user
spring.datasource.password=patient_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
server.port=4000

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Ciruit Breaker
resilience4j.circuitbreaker.instances.billingService.sliding-window-size=10
resilience4j.circuitbreaker.instances.billingService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.billingService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.billingService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.billingService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.billingService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.billingRetry.max-attempts=2
resilience4j.retry.instances.billingRetry.wait-duration=500ms   